language: node_js
os:
- windows
node_js:
- '8'
env:
  - secure:"iJPeh4C4/KAkfvHqmxLS3NlZMU70QLPnunHtC5KDfGxsiu7XU5g0EFDmIww6ejSLs1SijNcDWO1cVxm7/7EO/rFwQGaBg6PfnOk7hx6RRiS39HMsiE7jiPfrWs78LWwwR3/XYe+xS64Jza+qbyUDeRIl6UfW4VFDo/XRWWWTUkZamQwTV6YNCEJySQLJ9KGuPUWSxvKPF5k/2smjKR/pJ0IKIWVpgyJsioJAx/jMQCltTVDE6T2+Lt7Icr/9KEwdZ4krsZx4zhrrR/OaIRHro61kzCd+/znicHnv/WM837seNuTx6lnrL8P8kqlnBTSQoa76/xYdv+ffsbHw1ktK6D2758PB8Q6XxrKwjkTMGkZ7lS+n9SWXHfZJi3K2EdPl93Xm0+Nv474eYMRa0ZQvOTWDXtKab+0E7369DjiivOPIy4qvXoB7fsB6F5jA3+iGxVp6kSZZG4fnbRvmpySrLe3yJEPzgrY+lcewMIb+bewrZ7ivxy17kNLkIQfePLymh52fnoMYEPLGu3LAuPiED+dxTqMcFKjrZzdflYkJ55P6YvWuDPkN2zlK7sRrFNdULrpoGzceKX8kPgWXiPVUQnW76t9xEqO5GIUQ+osS6XJnArqQoZDHRTAlhADOW99BmAKLHUAMTuDkF/tQjo/vtx1Zp0eM7ow0C6I3y8/ZtW4="
before_install:
- npm install electron-builder -g
script:
  - electron-builder build -w --publish=always
